services:
  web:
    image: node:20-bullseye
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
