services:
  web:
    image: node:20-bullseye
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=https://localhost.com/api
      - NEXT_PUBLIC_COOKIE_DOMAIN=localhost.com
      - NEXT_PUBLIC_TRANSLATION_URL=https://localhost.com/fastapi
