import type { Metadata } from "next";
import "./globals.css";
import SideMenu from "@/SideMenu";
import HamburgerMenuCompo from "./components/HamburgerMenuCompo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="sm:ml-40 dark:bg-white dark:text-black">
      <SideMenu />
      <HamburgerMenuCompo/>
      {children}
    </div>
  );
}
